### ISSUE TITLE
As a todoApp, I want to be able to CRUD task_categories

### ISSUE THREAD

**Issue by Hyrlos** [Hyrlos/CERN_application_todo-web-app#4]
# TODO : 
Create, read, update, and delete  task_categories

**Dependancy** #1

## Implementation
- [x] task_categories controller
- [x]  task_categories repository
- [x]  task_categories service 

## Tests
- [x] Create
- [x] Read
- [x] Update
- [x] Delete
